language: node_js
node_js:
  - 8
  - 10
before_deploy:
  - cd site
  - npm install
  - npm run build
  - cp demo-small.mp4 demo.gif dist/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: site/dist
  on:
    branch: master
cache:
  directories:
    - "node_modules"